name: pull-request

on:
    pull_request:
        branches:
            - main

jobs:
    pull-request:
        name: pull-request
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x, 15.x]
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}
            - name: node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install
              run: npm ci
            - name: lint
              run: npm run lint
            - name: format
              run: npm run format
            - name: test
              run: npm test
            - name: build
              run: npm run build:prod
